// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoFutbolistico.App.Persistencia;

namespace TorneoFutbolistico.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Desempeño", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GolesContra")
                        .HasColumnType("int");

                    b.Property<int>("GolesFavor")
                        .HasColumnType("int");

                    b.Property<int>("PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosPerdidos")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Desempeños");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DesempeñoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEquipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DesempeñoId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEstadio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.NovedadPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<string>("JugadorInvolucrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<string>("Novedad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarjetasAmarillas")
                        .HasColumnType("int");

                    b.Property<int>("TarjetasRojas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NovedadesPartido");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Arbitroid")
                        .HasColumnType("int");

                    b.Property<string>("EquipoLocal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipoVisitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadioId")
                        .HasColumnType("int");

                    b.Property<string>("FechaHora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarcadorLocal")
                        .HasColumnType("int");

                    b.Property<int>("MarcadorVisitante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Arbitroid");

                    b.HasIndex("EstadioId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Documento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Arbitro", b =>
                {
                    b.HasBaseType("TorneoFutbolistico.App.Dominio.Persona");

                    b.Property<string>("Colegio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_A")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Arbitro");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.DirectorTecnico", b =>
                {
                    b.HasBaseType("TorneoFutbolistico.App.Dominio.Persona");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int")
                        .HasColumnName("DirectorTecnico_EquipoId");

                    b.Property<int>("Id_DS")
                        .HasColumnType("int");

                    b.HasIndex("EquipoId");

                    b.HasDiscriminator().HasValue("DirectorTecnico");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Jugador", b =>
                {
                    b.HasBaseType("TorneoFutbolistico.App.Dominio.Persona");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Id_P")
                        .HasColumnType("int");

                    b.Property<int>("N_equipo")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EquipoId");

                    b.HasDiscriminator().HasValue("Jugador");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Equipo", b =>
                {
                    b.HasOne("TorneoFutbolistico.App.Dominio.Desempeño", "Desempeño")
                        .WithMany()
                        .HasForeignKey("DesempeñoId");

                    b.Navigation("Desempeño");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Estadio", b =>
                {
                    b.HasOne("TorneoFutbolistico.App.Dominio.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Municipio", b =>
                {
                    b.HasOne("TorneoFutbolistico.App.Dominio.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Partido", b =>
                {
                    b.HasOne("TorneoFutbolistico.App.Dominio.Arbitro", "Arbitro")
                        .WithMany()
                        .HasForeignKey("Arbitroid");

                    b.HasOne("TorneoFutbolistico.App.Dominio.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId");

                    b.Navigation("Arbitro");

                    b.Navigation("Estadio");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.DirectorTecnico", b =>
                {
                    b.HasOne("TorneoFutbolistico.App.Dominio.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TorneoFutbolistico.App.Dominio.Jugador", b =>
                {
                    b.HasOne("TorneoFutbolistico.App.Dominio.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId");

                    b.Navigation("Equipo");
                });
#pragma warning restore 612, 618
        }
    }
}
